apiVersion: v1
kind: Service
metadata:
  labels:
    app: vcluster
  name: oteldemo-prom
  namespace: vcluster-oteldemo
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: syncer
    port: 6444
    protocol: TCP
    targetPort: 6444
  selector:
    app: vcluster
    release: oteldemo
  sessionAffinity: None
  type: ClusterIP
